/** Public, framework-independent API. Importing this module starts no service. */
export { createMcpServer } from './mcp'
export type { CreateMcpServerOptions, McpAuthenticationHandler } from './mcp'
export { GarminClient } from './client'
export type { GarminClientOptions } from './client'
export { GarminToolService } from './tool-service'
export type { GarminDataClient, GarminToolServiceOptions } from './tool-service'
export { resolveConfig, resolveAccountAlias } from './config'
export type { Config, ConfigEnvironment, GarminRegion } from './config'
export { createStderrLogger } from './logger'
export type { GarminLogger } from './logger'
